[package]
name = "git-deflorp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.6"
crc32fast = "1.4.0"
gix-hash = "0.10.3"
gix-pack = "0.31.0"
sha-1 = "0.10.1"
